# Generated by Django 5.1.5 on 2025-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='date_time',
            field=models.CharField(max_length=50),
        ),
    ]
