# Generated by Django 5.1.5 on 2025-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_img',
            field=models.ImageField(upload_to='static/img/menu'),
        ),
    ]
