# Generated by Django 5.1.5 on 2025-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menu_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='beverage',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_table',
            name='ordered_item',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
