# Generated by Django 5.1.5 on 2025-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_beverages_booking_table_beverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='beverage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
