# Generated by Django 5.1.5 on 2025-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_booking_table_beverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='ordered_item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
