# Generated by Django 5.1.5 on 2025-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_booking_table_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='beverage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='ordered_item',
            field=models.CharField(max_length=100),
        ),
    ]
