# Generated by Django 5.1.5 on 2025-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_booking_table_beverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='beverage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='ordered_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
