# Generated by Django 5.1.5 on 2025-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_booking_table_beverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='no_of_people',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='beverage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='ordered_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
