# Generated by Django 5.1.5 on 2025-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_booking_table_no_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='beverage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='no_of_people',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='ordered_item',
            field=models.CharField(max_length=50),
        ),
    ]
